# Author :  Oganezov Alexandre
# assisted by: Alexandre Braure; Hengsheng ZHAO; Thanh Cong Vo
#code généré à l'aide de PYQTdesigner

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NousContacter(object):

    # créations de différente fonctions
    def setupUiNousContacter(self, NousContacter):
        NousContacter.setObjectName("NousContacter")
        NousContacter.resize(504, 760)
        NousContacter.setMinimumSize(QtCore.QSize(504, 760))
        NousContacter.setMaximumSize(QtCore.QSize(504, 760))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        NousContacter.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logoApp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NousContacter.setWindowIcon(icon)
        NousContacter.setStyleSheet("background-color: rgb(57, 64, 65);")

        self.label_4 = QtWidgets.QLabel(NousContacter)
        self.label_4.setGeometry(QtCore.QRect(40, 480, 121, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("photo/Zhao Hengsheng.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(NousContacter)
        self.label_5.setGeometry(QtCore.QRect(40, 330, 121, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("photo/Vo Thanh Cong.jpeg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(NousContacter)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 121, 111))
        self.label_6.setStyleSheet("background-image: url(photo/Braure Alexandre.png);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("photo/Braure Alexandre.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(NousContacter)
        self.label_7.setGeometry(QtCore.QRect(40, 180, 121, 111))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("photo/Oganezov Alexandre.jpeg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(NousContacter)
        self.label.setGeometry(QtCore.QRect(40, 630, 121, 111))
        self.label.setStyleSheet("background-image: url(photo/Laurent Wendling.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photo/Laurent Wendling.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NousContacter)
        self.label_2.setGeometry(QtCore.QRect(200, 30, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(NousContacter)
        self.label_3.setGeometry(QtCore.QRect(200, 180, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(NousContacter)
        self.label_8.setGeometry(QtCore.QRect(200, 330, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setText("<html><head/><body><p><span style=\" font-family:\'Roboto\'; font-weight:600;\">Vo Thanh Cong </span></p><p><span style=\" font-family:\'Roboto\';\">Etudiant en deuxiéme année </span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Menbre du projet</span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">ii12348@etu.parisdescartes.fr</span><br/></p></body></html>")
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(NousContacter)
        self.label_9.setGeometry(QtCore.QRect(200, 480, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(NousContacter)
        self.label_10.setGeometry(QtCore.QRect(200, 630, 261, 101))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(NousContacter)
        QtCore.QMetaObject.connectSlotsByName(NousContacter)

    def retranslateUi(self, NousContacter):
        _translate = QtCore.QCoreApplication.translate
        NousContacter.setWindowTitle(_translate("NousContacter", "Application GFD-Nous contacter"))
        self.label_2.setText(_translate("NousContacter", "<html><head/><body><p><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Braure Alexandre</span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Etudiant en deuxiéme année </span></p><p>Membre du projet</p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">ii06383@etu.parisdescartes.fr</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("NousContacter", "<html><head/><body><p><span style=\" font-family:\'roboto\'; font-weight:600;\">Oganezov Alexandre</span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Etudiant en deuxiéme année </span></p><p>Membre du <span style=\" font-family:\'MS Shell Dlg 2\';\">projet</span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">ii09140@etu.parisdescartes.fr</span></p><p><br/></p></body></html>"))
        self.label_9.setText(_translate("NousContacter", "<html><head/><body><p><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Zhao Hengsheng</span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Etudiant en deuxiéme année </span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Membre du projet</span></p><p><span style=\" font-family:\'MS Shell Dlg 2\';\">hengsheng.zhao@etu.parisdescartes.fr</span></p><p><br/></p></body></html>"))
        self.label_10.setText(_translate("NousContacter", "<html><head/><body><p><span style=\" font-weight:600;\">Wendling  Laurent </span></p><p>Professeur à l\'université de Paris Descartes</p><p>Encadrant du projet</p><p>lwendlin@math-info.univ-paris5.fr<br/></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NousContacter = QtWidgets.QWidget()
    ui = Ui_NousContacter()
    ui.setupUiNousContacter(NousContacter)
    NousContacter.show()
    sys.exit(app.exec_())
